# Global options
baseURL = "http://das-snigdha.github.io/"
canonifyURLs = true
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en"
theme = "barks"
title = "Snigdha Das"
copyright = "&copy; Copyright 2025 Snigdha Das. Powered by the <a href=\"https://github.com/timothygebhard/barks\" target=\"_blank\" rel=\"noopener\">Barks</a> theme for <a href=\"https://gohugo.io/\" target=\"_blank\" rel=\"noopener\">Hugo</a>."
enableRobotsTXT = true

# Main menu
[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 2
[[menu.main]]
    name = "Research"
    url  = "/research"
    weight = 2
[[menu.main]]
    name = "Teaching"
    url  = "/teaching"
    weight = 3
[[menu.main]]
    name = "CV"
    url  = "/cv.pdf"
    weight = 4
    [menu.main.params]
    target = "_blank"
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

# Customization options
[params]

    [params.head]
        author = "Snigdha Das"
        custom_css = "/custom.css"
        description = "Statistics Ph.D. student at Texas A&M university"
        keywords = ["statistics", "academic", "PhD"]

    [params.navigation]
        show_navigation = true

    [params.footer]
        show_footer = true

    [params.typography]
        title_font = "Bree Serif"
        body_font = "Source Sans Pro"

    [params.colors]
        theme_color = "#333333"
        background_color = "#fcfbf9"
        text_color = "#333333"
        link_color = "#8b0000"

    [params.social]
        [params.social.email]
            name = "E-Mail"
            class = "fas fa-envelope"
            url = "mailto:snigdha@stat.tamu.edu"
            weight = 1
        [params.social.github]
            name = "GitHub"
            class = "fab fa-github"
            url = "https://github.com/das-snigdha"
            weight = 2
        [params.social.google_scholar]
            name = "Google Scholar"
            class = "ai ai-google-scholar"
            url = "https://scholar.google.com/citations?hl=en&authuser=1&user=-Zd0uEMAAAAJ"
            weight = 3
        #[params.social.institution]
        #    name = "My institution"
        #    class = "fas fa-university"
        #    url = ""
        #    weight = 5
        [params.social.linkedin]
            name = "LinkedIn"
            class = "fab fa-linkedin"
            url = "https://www.linkedin.com/in/snigdha-das1812/"
            weight = 4
        #[params.social.location]
        #    name = "Contact"
        #    class = "fas fa-map-marker-alt"
        #    url = "/contact/"
        #    weight = 5
        #[params.social.orcid]
        #    name = "ORCID iD"
        #    class = "fab fa-orcid"
        #    url = "https://orcid.org/0000-0002-8862-8649"
        #    weight = 7


# Options for Markdown renderer
[markup]

    [markup.goldmark.renderer]
        unsafe = true
        xHTML = true

    [markup.highlight]
        style = 'dracula'